name: default
channels:
- conda-forge
- nodefaults
dependencies:
- sphinx >=8.1.3,<9
- sphinx-rtd-theme >=3.0.1,<4
- breathe >=4.35.0,<5
- cmake >=3.31.4,<4
- doxygen >=1.12.0,<2
- sphinx-copybutton >=0.5.2,<0.6
- furo >=2024.8.6,<2025
- sphinx-inline-tabs >=2023.4.21,<2024
- sphinxext-opengraph >=0.9.1,<0.10
- pip
- pip:
  - sphinxemoji~=0.3.1
