[project]
authors = ["Stephane Rigaud <stephane.rigaud@pasteur.fr>"]
channels = ["conda-forge"]
description = "Add a short description here"
name = "clesperanto-doc"
platforms = ["linux-64", "osx-64", "win-64", "osx-arm64"]
version = "0.1.0"

[tasks]
clean = "make clean"
build = { cmd = "make html", depends-on = ["clean"] }

[dependencies]
sphinx = ">=8.1.3,<9"
